name:                di-polysemy
version:             0.0.2
github:              "nitros12/di-polysemy"
homepage:            https://github.com/nitros12/di-polysemy
bug-reports:         https://github.com/nitros12/di-polysemy/issues
license:             MIT
license-file:        LICENSE
author:              "Ben Simms"
maintainer:          "ben@bensimms.moe"
copyright:           2019 Ben Simms
category:            Logging
build-type:          Simple
extra-doc-files:
  - README.md
  - CHANGELOG.md
tested-with:         GHC == 8.6.5


synopsis:            DI logger for polysemy
description:         DI logger for polysemy


dependencies:
  - base >= 4.12
  - relude
  - polysemy >= 1.3
  - polysemy-plugin >= 0.2
  - di-core >= 1.0.4
  - di-handle >= 1.0.1
  - di-df1 >= 1.2
  - df1 >= 0.3.2
  - stm >= 2.5
  - safe-exceptions
  - true-name >= 0.1
  - template-haskell >= 2.14

library:
  ghc-options:
    - -fplugin=Polysemy.Plugin
    - -Wall
  source-dirs: src

default-extensions:
  - TemplateHaskell
  - RecursiveDo
  - CPP
  - AllowAmbiguousTypes
  - BlockArguments
  - NoMonomorphismRestriction
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - UndecidableInstances
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - DerivingVia
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - StandaloneDeriving
  - DeriveAnyClass
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadFailDesugaring
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - OverloadedLabels
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns
  - DuplicateRecordFields
  - TypeOperators
  - TypeApplications
  - RoleAnnotations
  - PatternSynonyms
